# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelPostavke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kratek_opis_dela_postavke', models.CharField(max_length=100)),
                ('opis_dela_postavke', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('norma_cas', models.IntegerField(default=0)),
                ('splošna_določila_dela_postavke', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Postavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kratek_opis', models.CharField(max_length=100)),
                ('opis_postavke', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('enota_mere', models.CharField(max_length=100)),
                ('norma_cas', models.IntegerField(default=0)),
                ('splošna_določila_postavke', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Skupina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_skupine', models.CharField(help_text='Vnos skupine del(Zemeljska,Zidarska,Betonska,)', max_length=200)),
                ('splošna_določila_skupine', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='VrstaDel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_vrste_del', models.CharField(max_length=200)),
                ('splošna_določila_vrste_del', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('skupina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.Skupina')),
            ],
        ),
        migrations.CreateModel(
            name='Zvrst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_zvrsti', models.CharField(help_text='Vnos skupine del(Gradbena,Obrtniška,..)', max_length=200)),
                ('splošna_določila_zvrsti', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='skupina',
            name='zvrst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.Zvrst'),
        ),
        migrations.AddField(
            model_name='postavka',
            name='vrsta_del',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.VrstaDel'),
        ),
        migrations.AddField(
            model_name='delpostavke',
            name='postavkae',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='popisi.Postavka'),
        ),
    ]
