# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelPostavke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kratek_opis_dela_postavke', models.CharField(max_length=100)),
                ('opis_dela_postavke', models.TextField(max_length=1000)),
                ('norma_cas', models.IntegerField(default=0)),
                ('splosna_dolocila_dela_postavke', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kratek_opis', models.CharField(max_length=100)),
                ('opis_postavke', models.TextField(max_length=1000)),
                ('enota_mere', models.CharField(max_length=100)),
                ('norma_cas', models.IntegerField(default=0)),
                ('splosna_dolocila_postavke', models.TextField(default='miha', max_length=1000)),
                ('del_postavke', models.ManyToManyField(to='popisi.DelPostavke')),
            ],
        ),
        migrations.CreateModel(
            name='Skupina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_skupine', models.CharField(help_text='Vnos skupine del(Zemeljska,Zidarska,..)', max_length=200)),
                ('splosna_dolocila_skupine', models.TextField(default='SKUPINA', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Vaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(default='miha', max_length=100)),
                ('naslov', models.TextField(default='ledine', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='VrstaDel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_vrste_del', models.CharField(help_text='Vnos skupine del(Izkopi,Zasipi,..)', max_length=200)),
                ('splosna_dolocila_vrste_del', models.TextField(default='splosšna določila vrste del', max_length=1000)),
                ('skupina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.Skupina')),
            ],
        ),
        migrations.CreateModel(
            name='Zvrst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_zvrsti', models.CharField(help_text='Vnos skupine del(Gradbena,Obrtniška,..)', max_length=200)),
                ('splosna_dolocila_zvrsti', models.TextField(default='splošna določila zvrsti', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='skupina',
            name='zvrst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.Zvrst'),
        ),
        migrations.AddField(
            model_name='postavka',
            name='vrsta_del',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.VrstaDel'),
        ),
    ]
