# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaja',
            name='ime',
            field=models.CharField(default='mihec', max_length=100),
        ),
    ]
