# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delpostavke',
            name='postavkae',
        ),
        migrations.AddField(
            model_name='postavka',
            name='del_postavke',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='popisi.DelPostavke'),
        ),
    ]
