# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0002_auto_20170228_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelDrugace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kratek_opis_dela_postavke', models.CharField(max_length=100)),
                ('opis_dela_postavke', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('norma_cas', models.IntegerField(default=0)),
                ('splošna_določila_dela_postavke', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('postavka', models.ManyToManyField(to='popisi.Postavka')),
            ],
        ),
    ]
