# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0002_auto_20170326_2129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vaja',
        ),
    ]
