# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0003_deldrugace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deldrugace',
            name='postavka',
        ),
        migrations.RenameField(
            model_name='delpostavke',
            old_name='splošna_določila_dela_postavke',
            new_name='splosna_dolocila_dela_postavke',
        ),
        migrations.RenameField(
            model_name='postavka',
            old_name='splošna_določila_postavke',
            new_name='splosna_dolocila_postavke',
        ),
        migrations.RenameField(
            model_name='skupina',
            old_name='splošna_določila_skupine',
            new_name='splosna_dolocila_skupine',
        ),
        migrations.RenameField(
            model_name='vrstadel',
            old_name='splošna_določila_vrste_del',
            new_name='splosna_dolocila_vrste_del',
        ),
        migrations.RenameField(
            model_name='zvrst',
            old_name='splošna_določila_zvrsti',
            new_name='splosna_dolocila_zvrsti',
        ),
        migrations.AlterField(
            model_name='delpostavke',
            name='opis_dela_postavke',
            field=models.TextField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='DelDrugace',
        ),
    ]
